sudo: required 
dist: trusty 

language: generic 
compiler:
  - gcc
python:
  - "2.7"

# notifications:
#   email:
#     on_success: always
#     on_failure: always


env:
  # global:
  #   # - BEFORE_SCRIPT='./your_custom_PREprocess.sh'
  #   - AFTER_SCRIPT='./tests/run_tests.sh'
  matrix:
    - USE_DEB=true  ROS_DISTRO="kinetic"   ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu

install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config

script: 
  - source .ci_config/travis.sh
